import type {
  Appointment,
  CarePlan,
  CarePlanItem,
  ChatThread,
  ContentItem,
  Event,
  MembershipPlan,
  Message,
  Practitioner,
  Product,
  Service,
  UserProfile,
} from '@/types/domain';
import { VANDECART_BASE_URL } from './constants';

export const MOCK_MEMBER_ID = 'member-001';
export const MOCK_AUTH_USER_ID = 'auth-001';
export const MOCK_PRACTITIONER_ID = 'prac-001';

export const mockProfile: UserProfile = {
  id: MOCK_MEMBER_ID,
  authUserId: MOCK_AUTH_USER_ID,
  role: 'member',
  firstName: 'Priya',
  lastName: 'Sharma',
  email: 'priya@example.com',
  phone: '+1 555-0100',
  timezone: 'America/New_York',
  country: 'US',
  emergencyContact: 'Raj Sharma +1 555-0101',
  onboardingComplete: true,
  createdAt: new Date().toISOString(),
};

export const mockPractitioners: Practitioner[] = [
  {
    id: 'prac-001',
    firstName: 'Dr. Ananya',
    lastName: 'Verma',
    credentials: 'BAMS, MD (Ayurveda)',
    specialty: 'Digestive & Lifestyle Disorders',
    location: 'Virtual / New Jersey',
    bio: '15+ years guiding members through personalized Ayurvedic wellness plans.',
    nextAvailable: new Date(Date.now() + 86400000).toISOString(),
  },
  {
    id: 'prac-002',
    firstName: 'Meera',
    lastName: 'Patel',
    credentials: 'BAMS, Yoga Therapist',
    specialty: 'Stress, Sleep & Yoga Therapy',
    location: 'Virtual',
    nextAvailable: new Date(Date.now() + 172800000).toISOString(),
  },
  {
    id: 'prac-003',
    firstName: 'Ravi',
    lastName: 'Krishnan',
    credentials: 'Wellness Coach, Panchakarma Specialist',
    specialty: 'Detox & Panchakarma',
    location: 'Edison, NJ',
    nextAvailable: new Date(Date.now() + 259200000).toISOString(),
  },
];

export const mockServices: Service[] = [
  {
    id: 'svc-001',
    name: 'Virtual Individual Consultation',
    description: 'One-on-one Ayurvedic wellness consultation via video.',
    durationMinutes: 60,
    priceCents: 14000,
    type: 'virtual',
    category: 'consultation',
  },
  {
    id: 'svc-002',
    name: 'Couples Consultation',
    description: 'Joint wellness session for you and your partner.',
    durationMinutes: 75,
    priceCents: 20000,
    type: 'both',
    category: 'consultation',
  },
  {
    id: 'svc-003',
    name: 'Ayurveda Wellness Consultation',
    description: 'Comprehensive dosha assessment and wellness planning.',
    durationMinutes: 60,
    priceCents: 15000,
    type: 'both',
    category: 'consultation',
  },
  {
    id: 'svc-004',
    name: 'Follow-up with Ayurvedic Consultant',
    description: '30-day progress review and plan adjustments.',
    durationMinutes: 30,
    priceCents: 7500,
    type: 'virtual',
    category: 'follow_up',
  },
  {
    id: 'svc-005',
    name: 'Panchakarma Consultation',
    description: 'Eligibility review and pre-care guidance for Panchakarma.',
    durationMinutes: 45,
    priceCents: 10000,
    type: 'both',
    category: 'panchakarma',
  },
  {
    id: 'svc-006',
    name: 'Lifestyle Members Session',
    description: 'Included session for active lifestyle members.',
    durationMinutes: 30,
    priceCents: 0,
    type: 'virtual',
    category: 'membership',
  },
];

const carePlanItems: CarePlanItem[] = [
  {
    id: 'item-001',
    carePlanId: 'plan-001',
    type: 'supplement',
    title: 'Morning Digestive Support',
    instructions: 'Take 1 capsule with warm water, 30 minutes before breakfast.',
    schedule: 'Daily · Morning',
    rationale: 'Supports gentle morning elimination and digestive fire (agni).',
    safetyNote: 'Consult your practitioner if pregnant or taking blood thinners.',
    productUrl: `${VANDECART_BASE_URL}/products/triphala-support`,
    sortOrder: 1,
    status: 'pending',
  },
  {
    id: 'item-002',
    carePlanId: 'plan-001',
    type: 'yoga',
    title: 'Gentle Morning Breathing',
    instructions: 'Practice alternate nostril breathing (Nadi Shodhana) for 5 minutes.',
    schedule: 'Daily · Morning',
    rationale: 'Balances nervous system and prepares body for the day.',
    safetyNote: 'Stop if dizzy. Practice on empty stomach.',
    mediaUrl: 'https://example.com/yoga/breathing',
    sortOrder: 2,
    status: 'pending',
  },
  {
    id: 'item-003',
    carePlanId: 'plan-001',
    type: 'yoga',
    title: 'Gentle Yoga Flow',
    instructions: '15-minute gentle sequence focusing on spine and hips.',
    schedule: 'Daily · Morning',
    rationale: 'Improves mobility and reduces morning stiffness.',
    mediaUrl: 'https://example.com/yoga/gentle-flow',
    sortOrder: 3,
    status: 'completed',
    completedAt: new Date().toISOString(),
  },
  {
    id: 'item-004',
    carePlanId: 'plan-001',
    type: 'nutrition',
    title: 'Warm Water Routine',
    instructions: 'Drink 1 cup warm water upon waking, before other beverages.',
    schedule: 'Daily · Upon waking',
    rationale: 'Awakens digestion and supports daily hydration rhythm.',
    sortOrder: 4,
    status: 'pending',
  },
  {
    id: 'item-005',
    carePlanId: 'plan-001',
    type: 'nutrition',
    title: 'Favor Warm, Cooked Meals',
    instructions: 'Choose warm soups, kitchari, and cooked vegetables over cold/raw foods.',
    schedule: 'Daily · All meals',
    rationale: 'Supports agni and reduces digestive strain.',
    sortOrder: 5,
    status: 'pending',
  },
  {
    id: 'item-006',
    carePlanId: 'plan-001',
    type: 'lifestyle',
    title: 'Evening Wind-Down',
    instructions: 'Dim lights by 9 PM. No screens 30 minutes before bed.',
    schedule: 'Daily · Evening',
    rationale: 'Supports natural sleep rhythm and cortisol balance.',
    sortOrder: 6,
    status: 'pending',
  },
  {
    id: 'item-007',
    carePlanId: 'plan-001',
    type: 'lifestyle',
    title: 'Stress Journaling',
    instructions: 'Write 3 things you are grateful for and one worry to release.',
    schedule: 'Daily · Evening',
    rationale: 'Cultivates mental clarity and emotional balance.',
    sortOrder: 7,
    status: 'pending',
  },
  {
    id: 'item-008',
    carePlanId: 'plan-001',
    type: 'detox',
    title: 'Panchakarma Orientation',
    instructions: 'Review pre-care guidelines before your orientation session.',
    schedule: 'Weekly · Review',
    rationale: 'Prepares you for safe, practitioner-guided detox if eligible.',
    safetyNote: 'Panchakarma requires practitioner approval.',
    sortOrder: 8,
    status: 'pending',
  },
];

export const mockCarePlan: CarePlan = {
  id: 'plan-001',
  memberId: MOCK_MEMBER_ID,
  practitionerId: MOCK_PRACTITIONER_ID,
  practitioner: mockPractitioners[0],
  status: 'active',
  title: 'Your Ayurvedic Wellness Plan',
  summary: 'A balanced plan supporting digestion, sleep, and daily energy.',
  goal: 'Improve digestion, reduce stress, and restore sleep quality',
  startDate: new Date(Date.now() - 14 * 86400000).toISOString(),
  nextReviewDate: new Date(Date.now() + 16 * 86400000).toISOString(),
  progressSummary: '72% adherence this week. Great progress on yoga practices.',
  items: carePlanItems,
};

export const mockAppointments: Appointment[] = [
  {
    id: 'appt-001',
    memberId: MOCK_MEMBER_ID,
    practitionerId: MOCK_PRACTITIONER_ID,
    practitioner: mockPractitioners[0],
    serviceId: 'svc-004',
    service: mockServices[3],
    appointmentType: 'virtual',
    status: 'confirmed',
    startsAt: new Date(Date.now() + 3 * 86400000).toISOString(),
    endsAt: new Date(Date.now() + 3 * 86400000 + 1800000).toISOString(),
    meetingUrl: 'https://zoom.us/j/placeholder-vande-wellness',
    paymentStatus: 'included',
    reasonForVisit: '30-day progress review',
  },
];

export const mockThreads: ChatThread[] = [
  {
    id: 'thread-001',
    memberId: MOCK_MEMBER_ID,
    category: 'care_plan',
    subject: 'Care Team',
    lastMessage: 'Your practitioner reviewed your progress. Keep up the morning routine!',
    lastMessageAt: new Date(Date.now() - 3600000).toISOString(),
    unreadCount: 1,
  },
  {
    id: 'thread-002',
    memberId: MOCK_MEMBER_ID,
    category: 'technical',
    subject: 'Support',
    lastMessage: 'How can we help you today?',
    lastMessageAt: new Date(Date.now() - 86400000).toISOString(),
    unreadCount: 0,
  },
];

export const mockMessages: Record<string, Message[]> = {
  'thread-001': [
    {
      id: 'msg-001',
      threadId: 'thread-001',
      senderId: MOCK_PRACTITIONER_ID,
      senderName: 'Dr. Ananya Verma',
      body: 'Namaste Priya! I reviewed your check-ins this week. Your morning yoga consistency is wonderful.',
      visibility: 'member',
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      isOwn: false,
    },
    {
      id: 'msg-002',
      threadId: 'thread-001',
      senderId: MOCK_MEMBER_ID,
      senderName: 'Priya Sharma',
      body: 'Thank you! I have a question about the evening supplement timing.',
      visibility: 'member',
      createdAt: new Date(Date.now() - 5400000).toISOString(),
      isOwn: true,
    },
    {
      id: 'msg-003',
      threadId: 'thread-001',
      senderId: MOCK_PRACTITIONER_ID,
      senderName: 'Dr. Ananya Verma',
      body: 'Your practitioner reviewed your progress. Keep up the morning routine!',
      visibility: 'member',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      isOwn: false,
    },
  ],
  'thread-002': [
    {
      id: 'msg-004',
      threadId: 'thread-002',
      senderId: 'support-001',
      senderName: 'Vande Support',
      body: 'How can we help you today?',
      visibility: 'member',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      isOwn: false,
    },
  ],
};

export const mockContent: ContentItem[] = [
  {
    id: 'content-001',
    title: 'Introduction to Ayurveda',
    description: 'Foundations of doshas, agni, and daily rhythms.',
    type: 'course',
    category: 'Ayurveda basics',
    durationMinutes: 120,
    progress: 35,
  },
  {
    id: 'content-002',
    title: 'Advanced Diet & Nutrition',
    description: 'Seasonal eating and personalized nutrition principles.',
    type: 'course',
    category: 'Nutrition and recipes',
    durationMinutes: 180,
  },
  {
    id: 'content-003',
    title: 'Yoga Therapy Foundations',
    description: 'Therapeutic sequences for stress and mobility.',
    type: 'course',
    category: 'Yoga videos',
    durationMinutes: 90,
    progress: 0,
  },
  {
    id: 'content-004',
    title: 'Abhyanga Self-Massage',
    description: 'Learn traditional warm oil massage techniques.',
    type: 'video',
    category: 'Ayurveda basics',
    durationMinutes: 25,
  },
  {
    id: 'content-005',
    title: 'Understanding Your Dosha',
    description: 'A gentle introduction to Vata, Pitta, and Kapha.',
    type: 'article',
    category: 'Ayurveda basics',
    durationMinutes: 10,
  },
  {
    id: 'content-006',
    title: 'Stress Management Webinar',
    description: 'Recorded session on nervous system regulation.',
    type: 'webinar',
    category: 'Webinars',
    durationMinutes: 60,
  },
];

export const mockEvents: Event[] = [
  {
    id: 'event-001',
    title: 'Meditation Circle',
    description: 'Guided group meditation for calm and clarity.',
    type: 'meditation',
    startsAt: new Date(Date.now() + 2 * 86400000).toISOString(),
    endsAt: new Date(Date.now() + 2 * 86400000 + 3600000).toISOString(),
    isVirtual: true,
    spotsRemaining: 12,
  },
  {
    id: 'event-002',
    title: 'Panchakarma Orientation',
    description: 'Learn what to expect from a Panchakarma program.',
    type: 'workshop',
    startsAt: new Date(Date.now() + 5 * 86400000).toISOString(),
    endsAt: new Date(Date.now() + 5 * 86400000 + 5400000).toISOString(),
    isVirtual: true,
    spotsRemaining: 8,
  },
  {
    id: 'event-003',
    title: 'Stress Management Webinar',
    description: 'Live expert session on Ayurvedic stress tools.',
    type: 'webinar',
    startsAt: new Date(Date.now() + 7 * 86400000).toISOString(),
    endsAt: new Date(Date.now() + 7 * 86400000 + 3600000).toISOString(),
    isVirtual: true,
    registered: true,
  },
  {
    id: 'event-004',
    title: 'Live Morning Yoga',
    description: 'Gentle group yoga class with certified instructor.',
    type: 'live_yoga',
    startsAt: new Date(Date.now() + 1 * 86400000).toISOString(),
    endsAt: new Date(Date.now() + 1 * 86400000 + 3600000).toISOString(),
    isVirtual: true,
    spotsRemaining: 20,
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-001',
    name: 'Triphala Digestive Support',
    category: 'Herbal Supplements',
    description: 'Traditional three-fruit blend for gentle digestive support.',
    suggestedUse: '1 capsule with warm water before breakfast.',
    safetyNote: 'Not recommended during pregnancy without practitioner guidance.',
    sku: 'VHP-TRIP-001',
    productUrl: `${VANDECART_BASE_URL}/products/triphala-digestive-support`,
    practitionerRecommended: true,
    priceCents: 2499,
  },
  {
    id: 'prod-002',
    name: 'Ashwagandha Calm Blend',
    category: 'Stress Support',
    description: 'Adaptogenic herbal support for stress resilience.',
    suggestedUse: '1 capsule with warm milk in the evening.',
    safetyNote: 'Consult practitioner if taking thyroid medication.',
    sku: 'VHP-ASH-002',
    productUrl: `${VANDECART_BASE_URL}/products/ashwagandha-calm`,
    practitionerRecommended: true,
    priceCents: 2999,
  },
  {
    id: 'prod-003',
    name: 'Home Detox Kit',
    category: 'Detox',
    description: 'Practitioner-guided home detox essentials.',
    suggestedUse: 'Follow your care plan instructions.',
    safetyNote: 'Use only under practitioner supervision.',
    sku: 'VDK-HOME-001',
    productUrl: `${VANDECART_BASE_URL}/products/home-detox-kit`,
    priceCents: 8900,
  },
];

export const mockMembershipPlans: MembershipPlan[] = [
  {
    id: 'mem-001',
    name: 'Members Only',
    description: 'Essential virtual care and member benefits.',
    priceCents: 9900,
    billingPeriod: 'monthly',
    entitlements: [
      { id: 'e1', key: 'consultations', label: 'Virtual consultations', value: '1/month' },
      { id: 'e2', key: 'messaging', label: 'Direct messaging', value: true },
      { id: 'e3', key: 'webinars', label: 'Webinar access', value: true },
      { id: 'e4', key: 'discount', label: 'VandeCart discount', value: '10%' },
    ],
    stripePriceId: 'price_members_only',
  },
  {
    id: 'mem-002',
    name: 'Member + Spouse',
    description: 'Shared wellness support for you and your partner.',
    priceCents: 14900,
    billingPeriod: 'monthly',
    featured: true,
    entitlements: [
      { id: 'e5', key: 'consultations', label: 'Virtual consultations', value: '2/month' },
      { id: 'e6', key: 'family', label: 'Family profiles', value: 2 },
      { id: 'e7', key: 'messaging', label: 'Direct messaging', value: true },
      { id: 'e8', key: 'yoga', label: 'Yoga video advice', value: true },
      { id: 'e9', key: 'discount', label: 'VandeCart discount', value: '15%' },
    ],
    stripePriceId: 'price_member_spouse',
  },
  {
    id: 'mem-003',
    name: 'Family Membership',
    description: 'Comprehensive care for the whole family.',
    priceCents: 19900,
    billingPeriod: 'monthly',
    entitlements: [
      { id: 'e10', key: 'consultations', label: 'Virtual consultations', value: '3/month' },
      { id: 'e11', key: 'family', label: 'Family profiles', value: 4 },
      { id: 'e12', key: 'messaging', label: 'Direct messaging', value: true },
      { id: 'e13', key: 'panchakarma', label: 'Panchakarma pricing', value: 'Member rate' },
    ],
    stripePriceId: 'price_family',
  },
  {
    id: 'mem-004',
    name: 'Global Ayurvedic Telehealth',
    description: 'Monthly virtual care for global members.',
    priceCents: 14000,
    billingPeriod: 'monthly',
    entitlements: [
      { id: 'e14', key: 'consultations', label: 'Monthly virtual consultation', value: 1 },
      { id: 'e15', key: 'messaging', label: 'Expert access', value: true },
      { id: 'e16', key: 'whatsapp', label: 'Weekly WhatsApp support', value: true },
      { id: 'e17', key: 'discount', label: 'Herbal product discount', value: '10%' },
    ],
    stripePriceId: 'price_global_telehealth',
  },
  {
    id: 'mem-005',
    name: 'Annual Global Telehealth',
    description: 'Best value annual telehealth plan.',
    priceCents: 149900,
    billingPeriod: 'annual',
    entitlements: [
      { id: 'e18', key: 'consultations', label: 'Monthly virtual consultation', value: 12 },
      { id: 'e19', key: 'webinars', label: 'Webinar access', value: true },
      { id: 'e20', key: 'panchakarma', label: 'Panchakarma discount', value: '15%' },
      { id: 'e21', key: 'yoga', label: 'Yoga video advice', value: true },
    ],
    stripePriceId: 'price_annual_telehealth',
  },
];

export const mockFamilyMembers = [
  {
    id: 'fam-001',
    memberId: MOCK_MEMBER_ID,
    firstName: 'Raj',
    lastName: 'Sharma',
    relationship: 'Spouse',
  },
];

export const mockBalanceTip =
  'Sip warm water mindfully this morning to kindle agni before your first meal.';
